-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 19:29:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema if0_35185317_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema if0_35185317_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `if0_35185317_db` DEFAULT CHARACTER SET utf8 ;
USE `if0_35185317_db` ;

-- -----------------------------------------------------
-- Table `if0_35185317_db`.`Linka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `if0_35185317_db`.`Linka` ;

CREATE TABLE IF NOT EXISTS `if0_35185317_db`.`Linka` (
  `id_linka` INT NOT NULL AUTO_INCREMENT,
  `číslo_linky` INT UNSIGNED NOT NULL,
  `meno_linky` VARCHAR(240) NOT NULL,
  PRIMARY KEY (`id_linka`),
  UNIQUE INDEX `číslo_linky_UNIQUE` (`číslo_linky` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `if0_35185317_db`.`Trasa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `if0_35185317_db`.`Trasa` ;

CREATE TABLE IF NOT EXISTS `if0_35185317_db`.`Trasa` (
  `id_trasa` INT NOT NULL AUTO_INCREMENT,
  `meno_trasy` VARCHAR(45) NULL,
  `info_trasy` VARCHAR(240) NULL,
  `id_linka` INT NOT NULL,
  PRIMARY KEY (`id_trasa`),
  UNIQUE INDEX `idTrasy_UNIQUE` (`id_trasa` ASC),
  CONSTRAINT `fk_Trasa_Linka`
    FOREIGN KEY (`id_linka`)
    REFERENCES `if0_35185317_db`.`Linka` (`id_linka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `if0_35185317_db`.`Zastávka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `if0_35185317_db`.`Zastávka` ;

CREATE TABLE IF NOT EXISTS `if0_35185317_db`.`Zastávka` (
  `id_zastávka` INT NOT NULL AUTO_INCREMENT,
  `meno_zastávky` VARCHAR(45) NULL,
  `adresa_zastávky` VARCHAR(45) NULL,
  PRIMARY KEY (`id_zastávka`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `if0_35185317_db`.`Úsek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `if0_35185317_db`.`Úsek` ;

CREATE TABLE IF NOT EXISTS `if0_35185317_db`.`Úsek` (
  `poradie_úseku` INT NOT NULL,
  `id_zastávka_začiatok` INT NOT NULL,
  `id_zastávka_koniec` INT NOT NULL,
  `meno_úseku` VARCHAR(45) NOT NULL,
  `dĺžka_úseku` VARCHAR(45) NULL,
  `cas_useku` TIME NOT NULL,
  `Úsekcol` VARCHAR(45) NULL,
  `id_trasa` INT NOT NULL,
  PRIMARY KEY (`poradie_úseku`, `id_zastávka_začiatok`, `id_zastávka_koniec`, `id_trasa`),
  INDEX `fk_Úsek_Zastávka1_idx` (`id_zastávka_začiatok` ASC) ,
  INDEX `fk_Úsek_Zastávka2_idx` (`id_zastávka_koniec` ASC) ,
  UNIQUE INDEX `id_úsek_UNIQUE` (`meno_úseku` ASC) ,
  INDEX `fk_Úsek_Trasa1_idx` (`id_trasa` ASC) ,
  CONSTRAINT `fk_Úsek_Zastávka1`
    FOREIGN KEY (`id_zastávka_začiatok`)
    REFERENCES `if0_35185317_db`.`Zastávka` (`id_zastávka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Úsek_Zastávka2`
    FOREIGN KEY (`id_zastávka_koniec`)
    REFERENCES `if0_35185317_db`.`Zastávka` (`id_zastávka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Úsek_Trasa1`
    FOREIGN KEY (`id_trasa`)
    REFERENCES `if0_35185317_db`.`Trasa` (`id_trasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `if0_35185317_db`.`Vozidlo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `if0_35185317_db`.`Vozidlo` ;

CREATE TABLE IF NOT EXISTS `if0_35185317_db`.`Vozidlo` (
  `id_vozidlo` INT NOT NULL AUTO_INCREMENT,
  `názov` VARCHAR(45) NULL,
  `druh_vozidla` VARCHAR(45) NULL,
  `značka_vozidla` VARCHAR(45) NULL,
  PRIMARY KEY (`id_vozidlo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `if0_35185317_db`.`Uživateľ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `if0_35185317_db`.`Uživateľ` ;

CREATE TABLE IF NOT EXISTS `if0_35185317_db`.`Uživateľ` (
  `id_uživateľ` INT NOT NULL AUTO_INCREMENT,
  `meno_uživateľa` VARCHAR(45) NULL,
  `priezvisko_uživateľa` VARCHAR(45) NULL,
  `tel_číslo_uživateľa` VARCHAR(45) NULL,
  `heslo_uživateľa` VARCHAR(45) NULL,
  `rola_uživateľa` VARCHAR(45) NULL,
  PRIMARY KEY (`id_uživateľ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `if0_35185317_db`.`Plánovaný spoj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `if0_35185317_db`.`Plánovaný spoj` ;

CREATE TABLE IF NOT EXISTS `if0_35185317_db`.`Plánovaný spoj` (
  `id_plán_trasy` INT NOT NULL AUTO_INCREMENT, 
  `začiatok_trasy` DATETIME NULL,
  `id_trasa` INT NOT NULL,
  `id_vozidlo` INT NOT NULL,
  `id_uživateľ_dispečer` INT NOT NULL,
  `id_uživateľ_šofér` INT NOT NULL,
  PRIMARY KEY (`id_plán_trasy`),
  INDEX `fk_Plánovaný spoj_Trasa1_idx` (`id_trasa` ASC) ,
  INDEX `fk_Plánovaný spoj_Vozidlo1_idx` (`id_vozidlo` ASC) ,
  INDEX `fk_Plánovaný spoj_Uživateľ1_idx` (`id_uživateľ_dispečer` ASC) ,
  INDEX `fk_Plánovaný spoj_Uživateľ1_idx1` (`id_uživateľ_šofér` ASC) ,
  CONSTRAINT `fk_trasa`
    FOREIGN KEY (`id_trasa`)
    REFERENCES `if0_35185317_db`.`Trasa` (`id_linka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vozidlo`
    FOREIGN KEY (`id_vozidlo`)
    REFERENCES `if0_35185317_db`.`Vozidlo` (`id_vozidlo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uživateľ_šofér`
    FOREIGN KEY (`id_uživateľ_dispečer`)
    REFERENCES `if0_35185317_db`.`Uživateľ` (`id_uživateľ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plánovaný spoj_Uživateľ1`
    FOREIGN KEY (`id_uživateľ_šofér`)
    REFERENCES `if0_35185317_db`.`Uživateľ` (`id_uživateľ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `if0_35185317_db`.`Údržba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `if0_35185317_db`.`Údržba` ;

CREATE TABLE IF NOT EXISTS `if0_35185317_db`.`Údržba` (
  `id_údržba` INT NOT NULL AUTO_INCREMENT,
  `začiatok_údržby` DATETIME NULL,
  `id_vozidlo` INT NOT NULL,
  `id_uživateľ_správca` INT NOT NULL,
  PRIMARY KEY (`id_údržba`),
  INDEX `fk_Údržba_Vozidlo1_idx` (`id_vozidlo` ASC),
  INDEX `fk_Údržba_Uživateľ1_idx` (`id_uživateľ_správca` ASC),
  CONSTRAINT `fk_Údržba_Vozidlo1`
    FOREIGN KEY (`id_vozidlo`)
    REFERENCES `if0_35185317_db`.`Vozidlo` (`id_vozidlo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Údržba_Uživateľ1`
    FOREIGN KEY (`id_uživateľ_správca`)
    REFERENCES `if0_35185317_db`.`Uživateľ` (`id_uživateľ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `if0_35185317_db`.`Záznam údržby`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `if0_35185317_db`.`Záznam údržby` ;

CREATE TABLE IF NOT EXISTS `if0_35185317_db`.`Záznam údržby` (
  `id_údržba` INT NOT NULL,
  `id_uživateľ_technik` INT NOT NULL,
  INDEX `fk_Záznam údržby_Údržba1_idx` (`id_údržba` ASC) ,
  INDEX `fk_Záznam údržby_Uživateľ1_idx` (`id_uživateľ_technik` ASC),
  PRIMARY KEY (`id_údržba`, `id_uživateľ_technik`),
  CONSTRAINT `fk_Záznam údržby_Údržba1`
    FOREIGN KEY (`id_údržba`)
    REFERENCES `if0_35185317_db`.`Údržba` (`id_údržba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Záznam údržby_Uživateľ1`
    FOREIGN KEY (`id_uživateľ_technik`)
    REFERENCES `if0_35185317_db`.`Uživateľ` (`id_uživateľ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
